# Generated by Django 2.2.6 on 2020-05-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date creation'),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis_app.Client'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_emission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date emission'),
        ),
        migrations.AlterField(
            model_name='emeteur',
            name='fax',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ligneprix',
            name='grille_prix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis_app.GrillePrix'),
        ),
    ]
