# Generated by Django 2.2.6 on 2020-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0002_auto_20200519_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='titre',
            field=models.CharField(default='Titre devis par défault', max_length=200),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='date creation'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_emission',
            field=models.DateField(blank=True, null=True, verbose_name='date emission'),
        ),
    ]
