# Generated by Django 2.2.6 on 2020-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0005_auto_20200623_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_emission',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
