# Generated by Django 2.2.6 on 2020-07-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0006_auto_20200706_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_emission',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
