# Generated by Django 2.2.6 on 2020-08-05 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0008_auto_20200805_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name=['%d/%m/%Y']),
        ),
    ]
