# Generated by Django 2.2.6 on 2020-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0009_auto_20200805_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
