# Generated by Django 2.2.6 on 2020-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0010_auto_20200812_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprix',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
