# Generated by Django 2.2.6 on 2020-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis_app', '0011_ligneprix_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='grilleprix',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligneprix',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
